services:
    _defaults:
        autowire: true
        autoconfigure: true

    IWD\SymfonyEntryContract\:
        resource: '../../../src/*'
        exclude:
            - '../../../src/DependencyInjection/'

    IWD\SymfonyEntryContract\Service\Validator\Interfaces\ValidatorService:
        class: IWD\SymfonyEntryContract\Service\Validator\Implementation\ValidatorService

    IWD\SymfonyEntryContract\Core\Dto\Locale:
        arguments: [ '%locale%' ]

    IWD\SymfonyEntryContract\Service\RequestParser\Interfaces\LocaleMakerInterface:
        class: IWD\SymfonyEntryContract\Service\RequestParser\Implementations\LocaleMaker

    IWD\SymfonyEntryContract\Service\Factory\Interfaces\InputContractFactoryInterface:
        class: IWD\SymfonyEntryContract\Service\Factory\Implementations\InputContractFactory

    IWD\SymfonyEntryContract\Service\RequestParser\Interfaces\RequestParserInterface:
        class: IWD\SymfonyEntryContract\Service\RequestParser\Implementations\RequestParser
